name: ◡🥀𝓐𝓸𝓲𝓒𝓱𝓪𝓷🥀◡【👻】

# Bật/tắt upload Artifact ( .jar )
env:
  ENABLE_ARTIFACT: false

on:
  push:
    branches: [ main ]
    #workflow_dispatch:

permissions:
  actions: write
  contents: read
  
jobs:
  aoichan:
    name: ◡🥀𝓐𝓸𝓲𝓒𝓱𝓪𝓷🥀◡
    runs-on: ubuntu-latest
    
    steps:
      - name: 🔎𝓒𝓱𝓮𝓬𝓴 𝓢𝓸𝓾𝓻𝓬𝓮
        uses: actions/checkout@v6
          
      # Đóng gói file .jar
      - name: 📦 𝓤𝓹𝓵𝓸𝓪𝓻𝓭 𝓳𝓪𝓻
        if: ${{ env.ENABLE_ARTIFACT == 'true' }}
        uses: actions/upload-artifact@v5
        with:
          name: Resource-Packs
          path: .

      # Tự động dọn dẹp Workflows Runs 【 5 Runs 】
      - name: ♻️𝐎𝐋𝐃 𝐖𝐎𝐑𝐊𝐅𝐋𝐎𝐖𝐒
        run: |
          gh api repos/${{ github.repository }}/actions/runs \
            --paginate \
            --jq '.workflow_runs | sort_by(.created_at) | reverse | .[1:] | map(select(.status=="completed")) | .[].id' \
            | while read run; do
                echo "🗑️ đã xóa $run"
                gh api repos/${{ github.repository }}/actions/runs/$run -X DELETE
              done
        env:
          GH_TOKEN: ${{ secrets.AOI_RESOURCES }}

      - name: ♻️𝐎𝐋𝐃 𝐂𝐀𝐂𝐇𝐄
        run: |
          gh cache list --json id,createdAt \
            | jq 'sort_by(.createdAt) | reverse | .[1:] | .[].id' \
            | while read id; do
                echo "🗑️ đã xóa $id"
                gh cache delete "$id"
              done
        env:
          GH_TOKEN: ${{ secrets.AOI_RESOURCES }}
